# Action name
name: Docker101

# Trigger
on: push

# What to do  when a 'push' event triggered
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest 
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      BUILD_TIME: ${`date "+%Y%m%d%H%M%S"`}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: set build time
        id: set_build_time
        run: echo ::set-env name=BUILD_TIME::$(echo ${`date "+%Y%m%d%H%M%S"`})
      - name: Get release version
        id: get_version
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_SHA:0:6}-${{ env.BUILD_TIME }})
      - name: echo docker tag
        id: echo_tag
        run: echo  ${{ env.RELEASE_VERSION }}
      - name: Build and push image to dockerhub
        uses: lth2015/Publish-Docker-Github-Action@master
        with:
          name: ${{ secrets.IMAGE_NAME }}
          # docker build -t template-go -f build/docker/Dockerfile .
          dockerfile: php/Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          tags: "latest,${{ env.RELEASE_VERSION }}"
