# Action name
name: Docker101

# Trigger
on: push

# What to do  when a 'push' event triggered
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest 
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: UNSECURE env
        id: set UNSECURE env
        run: echo ::set-env name=ACTIONS_ALLOW_UNSECURE_COMMANDS::true
      - name: Get release version
        id: get_version
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_SHA:6})
      - name: Build and push image to dockerhub
        uses: lth2015/Publish-Docker-Github-Action@master
        with:
          name: ${{ secrets.IMAGE_NAME }}
          # docker build -t template-go -f build/docker/Dockerfile .
          dockerfile: php/Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          tags: "latest,${{ env.RELEASE_VERSION }}"